name: Feature Request
description: Suggest a new idea or enhancement for the software.
labels: [feature]
body:
- type: markdown
  attributes:
    value: |
      Feature requests are for suggesting **new functionality or improvements** to the existing software.
      If you’re reporting a bug, please use the *Bug Report* form instead.
      For help installing or configuring the software, please visit our Discord server.

- type: textarea
  attributes:
    label: Feature Description
    description: Please provide a clear and concise description of the feature or enhancement you’d like to see.
  validations:
    required: true

- type: textarea
  attributes:
    label: Problem Statement
    description: Explain what problem this feature would solve or what need it addresses.
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional Context
    description: Add any other context, references, or screenshots related to your request.
  validations:
    required: false
